### ISSUE TITLE
LegacySamExtensionService cannot be resolved 

### ISSUE THREAD

**Issue by NavnathDodeg** [eclipse-keyple/keyple-card-calypso-java-lib#105]
i am using it for createSamSelection but getting error LegacySamExtensionService cannot be resolved

**Comment by NavnathDodeg** [comment]
also getting same error for LegacySam and LegacySamUtil

**Comment by andrei-cristea** [comment]
Hi,

Your project seems to be missing the Legacy SAM library import.

I recommend that you use the following [configuration tool](https://keyple.org/components/overview/configuration-wizard/) available on the official [keyple.org](keyple.org) website to import properly the Keyple libraries into your project.

**Comment by NavnathDodeg** [comment]
Hi andrei-cristea

> Hi,
> 
> Your project seems to be missing the Legacy SAM library import.
> 
> I recommend that you use the following [configuration tool](https://keyple.org/components/overview/configuration-wizard/) available on the official [keyple.org](keyple.org) website to import properly the Keyple libraries into your project.



as you said everything is up to date and every library mentioned in that article is added still getting same error. my java version is 20 and gradle is 8.3

**Comment by NavnathDodeg** [comment]
Solved. thank you.
