### ISSUE TITLE
The method createSymmetricCryptoCardTransactionManagerFactory(CardReader, LegacySam) in the type LegacySamApiFactory is not applicable for the arguments (CardReader, SmartCard)

### ISSUE THREAD

**Issue by NavnathDodeg** [eclipse-keyple/keyple-card-calypso-java-lib#106]
The method createSymmetricCryptoCardTransactionManagerFactory(CardReader, LegacySam) in the type LegacySamApiFactory is not applicable for the arguments (CardReader, SmartCard)

what to pass in arguement at LegacySam ?

**Comment by NavnathDodeg** [comment]
Hi Jean-Pierre Fortune,
The method getCalypsoCard() is undefined for the type SecureExtendedModeTransactionManager

The method processOpening(WriteAccessLevel) is undefined for the type SecureExtendedModeTransactionManager

The method prepareReleaseCardChannel() is undefined for the type SecureExtendedModeTransactionManager

previously it was in cardTransactionManager

**Comment by jeanpierrefortune** [comment]
The migration guide is available here: https://keyple.org/learn/user-guide/migration-guide/
