### ISSUE TITLE
The method getSmartCard() from the type CardResource refers to the missing type SmartCard

### ISSUE THREAD

**Issue by NavnathDodeg** [eclipse-keyple/keyple-card-calypso-java-lib#107]
1.The method getSmartCard() from the type CardResource refers to the missing type SmartCard

2.The method getReader() from the type CardResource refers to the missing type CardReader

3.The method getCalypsoCard() is undefined for the type SecureExtendedModeTransactionManager(previosly getCalypsoCard() was in CardTransactionManager)

4.The method processOpening(WriteAccessLevel) is undefined for the type SecureExtendedModeTransactionManager(previosly processOpening was in CardTransactionManager)

5.The method prepareReleaseCardChannel() is undefined for the type SecureExtendedModeTransactionManager

**Comment by jeanpierrefortune** [comment]
The migration guide is available here: https://keyple.org/learn/user-guide/migration-guide/
