### ISSUE TITLE
TRANSMIT_CARD_REQUEST remote service does not align with the JSON api

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse-keyple/keyple-card-calypso-java-lib#115]
When sending a card request to a remote reader, one of the parameters does not align with the JSON API

```JSON
{
"service":"TRANSMIT_CARD_REQUEST",
    "parameters":{
        "cardRequest":{
            "apduRequests":[
                {
                    "apdu":"008A0B39041E8F3E2A00",
                    "info":"Open Secure Session - KEYINDEX:3, SFI:07h, REC:1",
                    "successfulStatusWords":[
                        "9000"
                     ]
               }
            ],
           "isStatusCodesVerificationEnabled":true
        },
    "channelControl":"KEEP_OPEN"
    }
}
```

`isStatusCodesVerificationEnabled` should be `stopOnUnsuccessfulStatusWord`

I think the issue comes from the name here
https://github.com/eclipse-keyple/keyple-card-calypso-java-lib/blob/4dda5d0b35be56cf180448882f3d1ce1386af52a/src/main/java/org/eclipse/keyple/card/calypso/DtoAdapters.java#L158

Regards,

**Comment by andrei-cristea** [comment]
Hi Aghilas, it's fixed, but publication on sonatype is still impossible for the moment because of the infra. Regards

**Comment by andrei-cristea** [comment]
Hi Aghilas,

The fix is now available in the following versions:

- `org.eclipse.keyple:keyple-card-calypso-java-lib:3.1.2`
- `org.eclipse.keyple:keyple-card-calypso-java-lib:2.3.11`

Regards
